### ISSUE TITLE
Changelog for foobar2000 is impossible to read in every theme

### ISSUE THREAD

**Issue by mxxcon** [anod/AppWatcher#101]
App https://play.google.com/store/apps/details?id=com.foobar2000.foobar2000

If I set app's theme to white, it's displaying white text on white background
If I set app's theme to dark or black, it's displaying extremely dark text on black background.
![Screenshot_20230728_155449_App Watcher](https://github.com/anod/AppWatcher/assets/847140/9b3f681a-7dd8-486c-92af-3814198fafbf)
![Screenshot_20230728_155502_App Watcher](https://github.com/anod/AppWatcher/assets/847140/87efe61c-d54b-4b86-be92-6cfbf64d0b0e)
![Screenshot_20230728_155521_App Watcher](https://github.com/anod/AppWatcher/assets/847140/9254a35b-4858-472a-99b6-b6a20085037e)

**Comment by anod** [comment]
Published a fix in beta channel

**Comment by mxxcon** [comment]
I'm running v1.6.0 and this problem still exist.

**Comment by anod** [comment]
it's still in beta
