### ISSUE TITLE
Can't choose account on Android Nougat

### ISSUE THREAD

**Issue by yochananmarqos** [anod/AppWatcher#40]
Tapping on the selected account (see screenshot) does nothing and the app will not sync with the Play Store. I'm still able to use the app normally otherwise and can enable Google Drive sync. 

![screenshot_20160826-104455](https://cloud.githubusercontent.com/assets/5437803/18013230/6ef2ba98-6b7a-11e6-97b6-dde2b915b84f.png)

App Watcher 1.8.3
Android 7.0 NRD90M
Nexus 5X

**Comment by anod** [comment]
The buttons are there, the text is white on Android N for some reason. Fixed in the upcoming version
