### ISSUE TITLE
RFE: Please keep /releases updated

### ISSUE THREAD

**Issue by TPS** [anod/AppWatcher#69]
https://github.com/anod/AppWatcher/releases/tag/latest = https://github.com/anod/AppWatcher/releases/tag/v1.7.1 , while it _should_ be @ least v1.8.9 per GPlay.

Thanks!  Just discovered your app. Quite cool!

**Comment by anod** [comment]
Will try to keep updated

**Comment by TPS** [comment]
Thanks for the quick update. :bow:
