### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by emjatin** [anod/AppWatcher#72]
App_Watcher-1.9.1b64
Unable to run on Redmi 2 Prime Based on MIUI 8 Dev. With Lollipop 5.1
Restarting again and again.

**Comment by anod** [comment]
Hi

There's a problem with MIUI theme service and some icon which cause the error, I don't have a miui device and cannot reproduce it. 

Is it first time that you open the app? Is the error happening all the time or you are able to open it sometimes? 

I can do some changes in the app and send you a build to test, if you mail me to alex.gavrishev@gmail.com

**Comment by anod** [comment]
Do you use some custom theme, or custom icon? 
There are some errors related to Xposed, do you use it? 

In the last 24 hrs I see crash on Redmi Note 3 and 
Redmi 4X (and not yours) with the following error 
Exception java.lang.IllegalStateException: Can't parcel a recycled bitmap
android.graphics.Bitmap.checkRecycled (Bitmap.java:363)
android.graphics.Bitmap.writeToParcel (Bitmap.java:1552)
miui.content.res.IThemeService$Stub$Proxy.saveCustomizedIcon (IThemeService.java:177)
miui.content.res.ThemeRuntimeManager.saveIconInner (ThemeRuntimeManager.java:223)
miui.content.res.ThemeRuntimeManager.access$600 (ThemeRuntimeManager.java:36)
miui.content.res.ThemeRuntimeManager$ThemeServiceThread.run (ThemeRuntimeManager.java:199)
Data

**Comment by emjatin** [comment]
Thankyou For Your Response

I am Using Default Theme Of MiUi 8
And from Last 3 Updates I am facing this Issue.
Otherwise it is Working Fine.

Yes i am Using Xposed but I try App after Fully removing Xposed But it give Same Results.

Its my Mail Address

Mailallatone@gmail.com

**Comment by anod** [comment]
@emjatin 
Please try the new beta, I changed app icon location a little bit, it might help, otherwise I will have to create separate builds to identify the issue

**Comment by emjatin** [comment]
I try New Beta Update But Problem Remains Same.

Should i Send You my system Log ???

**Comment by anod** [comment]
I will create couple of different versions of the app in following days and will send you in mail to test where is the problem might be

Sincerely 
Alex

**Comment by emjatin** [comment]
Thanks
