### ISSUE TITLE
F-droid Release

### ISSUE THREAD

**Issue by bb1a2** [anod/AppWatcher#78]
Hi,

Thanks for the app :) I used to use ApkTrack but it barely works anymore.

Can you please release your app on F-Droid. I'm sure a lot of folks there will find it specially useful.

You can find more information [here](https://f-droid.org/docs/FAQ_-_App_Developers/?title=FAQ_-_App_Developers).

Cheers :)

**Comment by anod** [comment]
I looked once to add the app to F-Droid, but the app heavily depends on google services for users to access their apps data in play store

https://f-droid.org/docs/Inclusion_Policy/
We cannot build apps using Google’s proprietary “play-services”. Please talk to upstream about an untainted build flavor (either using microg or removing non-free dependencies completely).
